// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.3 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
)

// Defines values for AlertStatus.
const (
	Acked    AlertStatus = "acked"
	Firing   AlertStatus = "firing"
	Resolved AlertStatus = "resolved"
	Silenced AlertStatus = "silenced"
	TimedOut AlertStatus = "timed out"
)

// Defines values for GetAlertsParamsOrder.
const (
	GetAlertsParamsOrderASC  GetAlertsParamsOrder = "ASC"
	GetAlertsParamsOrderDESC GetAlertsParamsOrder = "DESC"
)

// Defines values for GetSilencesParamsOrder.
const (
	GetSilencesParamsOrderASC  GetSilencesParamsOrder = "ASC"
	GetSilencesParamsOrderDESC GetSilencesParamsOrder = "DESC"
)

// Alert defines model for Alert.
type Alert struct {
	Acknowledgement *AlertAcknowledgement `json:"acknowledgement,omitempty"`
	Annotations     map[string]string     `json:"annotations"`
	EndsAt          *time.Time            `json:"endsAt,omitempty"`
	Id              *string               `json:"id,omitempty"`
	Labels          map[string]string     `json:"labels"`
	StartsAt        time.Time             `json:"startsAt"`
	Status          AlertStatus           `json:"status"`
	TimeoutDeadline *time.Time            `json:"timeoutDeadline,omitempty"`
}

// AlertStatus defines model for Alert.Status.
type AlertStatus string

// AlertAcknowledgement defines model for AlertAcknowledgement.
type AlertAcknowledgement struct {
	AlertID *string `json:"alertID,omitempty"`
	Comment string  `json:"comment"`
	Creator string  `json:"creator"`
}

// Matcher defines model for Matcher.
type Matcher struct {
	IsNegative bool   `json:"isNegative"`
	IsRegex    bool   `json:"isRegex"`
	Label      string `json:"label"`
	Value      string `json:"value"`
}

// Silence defines model for Silence.
type Silence struct {
	Comment  string    `json:"comment"`
	Creator  string    `json:"creator"`
	EndsAt   time.Time `json:"endsAt"`
	Id       *string   `json:"id,omitempty"`
	Matchers []Matcher `json:"matchers"`
	StartsAt time.Time `json:"startsAt"`
}

// StatsResult defines model for StatsResult.
type StatsResult struct {
	Frames [][]float32       `json:"frames"`
	Labels map[string]string `json:"labels"`
}

// AcknowledgeAlert defines model for AcknowledgeAlert.
type AcknowledgeAlert = AlertAcknowledgement

// PostAlerts defines model for PostAlerts.
type PostAlerts = []Alert

// PostSilence defines model for PostSilence.
type PostSilence = Silence

// GetAlertsParams defines parameters for GetAlerts.
type GetAlertsParams struct {
	// Limit The maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The offset into the results to return. Used for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort The fields to sort the results by
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order The order of the results. Only valid if `sort` is also specified.
	Order *GetAlertsParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Matchers The matchers used to filter the returned list. Only alerts that match all the matchers will be returned.
	Matchers *[]string `form:"matchers,omitempty" json:"matchers,omitempty"`
}

// GetAlertsParamsOrder defines parameters for GetAlerts.
type GetAlertsParamsOrder string

// PostAlertsJSONBody defines parameters for PostAlerts.
type PostAlertsJSONBody = []Alert

// GetAlertsStatsParams defines parameters for GetAlertsStats.
type GetAlertsStatsParams struct {
	Type string `form:"type" json:"type"`

	// Args The arguments to the query, depending on the query type.
	Args *map[string]string `form:"args,omitempty" json:"args,omitempty"`
}

// GetSilencesParams defines parameters for GetSilences.
type GetSilencesParams struct {
	// Limit The maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The offset into the results to return. Used for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort The fields to sort the results by
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order The order of the results. Only valid if `sort` is also specified.
	Order *GetSilencesParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Matchers The matchers used to filter the returned list. Only silences that match all the matchers will be returned.
	// Note that matchers are applied literally to silences, e.g. sending `instance=~foo` will _only_ return silences
	// which contain the matcher `instance=~foo`
	Matchers *[]string `form:"matchers,omitempty" json:"matchers,omitempty"`
}

// GetSilencesParamsOrder defines parameters for GetSilences.
type GetSilencesParamsOrder string

// PostAlertsJSONRequestBody defines body for PostAlerts for application/json ContentType.
type PostAlertsJSONRequestBody = PostAlertsJSONBody

// PostAlertsAckJSONRequestBody defines body for PostAlertsAck for application/json ContentType.
type PostAlertsAckJSONRequestBody = AlertAcknowledgement

// PostSilencesJSONRequestBody defines body for PostSilences for application/json ContentType.
type PostSilencesJSONRequestBody = Silence

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get alerts details
	// (GET /alerts)
	GetAlerts(w http.ResponseWriter, r *http.Request, params GetAlertsParams)
	// Add, or update alerts
	// (POST /alerts)
	PostAlerts(w http.ResponseWriter, r *http.Request)
	// Acknowledge an alert
	// (POST /alerts/ack)
	PostAlertsAck(w http.ResponseWriter, r *http.Request)
	// Query aggregated stats about alerts in the system
	// (GET /alerts/stats)
	GetAlertsStats(w http.ResponseWriter, r *http.Request, params GetAlertsStatsParams)
	// Get silences
	// (GET /silences)
	GetSilences(w http.ResponseWriter, r *http.Request, params GetSilencesParams)
	// Silence alerts
	// (POST /silences)
	PostSilences(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetAlerts operation middleware
func (siw *ServerInterfaceWrapper) GetAlerts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlertsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "matchers" -------------

	err = runtime.BindQueryParameter("form", true, false, "matchers", r.URL.Query(), &params.Matchers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "matchers", Err: err})
		return
	}

	handler := func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlerts(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostAlerts operation middleware
func (siw *ServerInterfaceWrapper) PostAlerts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAlerts(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostAlertsAck operation middleware
func (siw *ServerInterfaceWrapper) PostAlertsAck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAlertsAck(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetAlertsStats operation middleware
func (siw *ServerInterfaceWrapper) GetAlertsStats(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlertsStatsParams

	// ------------- Required query parameter "type" -------------

	if paramValue := r.URL.Query().Get("type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "args" -------------

	err = runtime.BindQueryParameter("form", true, false, "args", r.URL.Query(), &params.Args)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "args", Err: err})
		return
	}

	handler := func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlertsStats(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetSilences operation middleware
func (siw *ServerInterfaceWrapper) GetSilences(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSilencesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "matchers" -------------

	err = runtime.BindQueryParameter("form", true, false, "matchers", r.URL.Query(), &params.Matchers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "matchers", Err: err})
		return
	}

	handler := func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSilences(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostSilences operation middleware
func (siw *ServerInterfaceWrapper) PostSilences(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSilences(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/alerts", wrapper.GetAlerts).Methods("GET")

	r.HandleFunc(options.BaseURL+"/alerts", wrapper.PostAlerts).Methods("POST")

	r.HandleFunc(options.BaseURL+"/alerts/ack", wrapper.PostAlertsAck).Methods("POST")

	r.HandleFunc(options.BaseURL+"/alerts/stats", wrapper.GetAlertsStats).Methods("GET")

	r.HandleFunc(options.BaseURL+"/silences", wrapper.GetSilences).Methods("GET")

	r.HandleFunc(options.BaseURL+"/silences", wrapper.PostSilences).Methods("POST")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYXY/bthL9KwTvBe6LrneTe/tioA9OtggWRdI0TvuSDbJjcWQzS5EKSa1jBO5vL4ai",
	"vlZU9iNNigJ5syVy5syZ4eGMPvHclJXRqL3jy0/c4ocanX9ihMTwYJVfabNXKLa4Umg9PcuN9qjDT6gq",
	"JXPw0uiT985oeubyHZZAv/5tseBL/q+T3slJ89adBGsD6yVZPB6PGRfocisrssmX/Dl6EOCB7XeoGXQb",
	"pN4y0AwCqGPGXxrng013L4jSY+nuhJWc+EOFfMnBWjikwDYAmDcMhMiYsayuBHhkUjO/Q+YOzmO5aPGu",
	"pUKd41/GaWsvhYy55mUEx2lJ3Bfy3Ca3sqZC62P64UaCHpTUjIPWxoeIGqtCSPoD6uXIW6TXeSv1dsC3",
	"2bzHPBhCLdwqwCiMLcHzJSd+/+tliTybGpCiqWoQv2h14Etva0wsU7BB9YXQnAfr7wXOefB1sI66Lvny",
	"DS9keJcR7yh4xi06o67DT7IimKk9z3jMpeBvE2Zpoan9GYJQUuMsnltYOWZBDaRFQdAkYYg8jRPaBTLg",
	"YIribYKyZLlMa5BWnZ9Ns5DxvZUe+xiOGclZa2VCTG4RvLGJdzdibT32W3rDqTieg893aKfQpXuBW/Dy",
	"GgdON8YoBB3K073CLX5MvwxkJwO5BlXj7WE0BtrlvbdsiCsVz0CXxvE8jN2vdmzLhnd3ZyFvEzWR8vsf",
	"39TxmFbL6EhEFga4k+R78O4VulolzkJhocRxvN2PDnWhDPgesa7LTTrmm/+/XAZTFUjCEHFP46UdUhcm",
	"GJde0bvfHzFTsJ+lsfAfx1Yvz6mG0brmJnu0OF2ckmtToYZK8iX/X3iU8Qr8LsA8ga4T2GKgcXwbvoYr",
	"dNQ+mKqJkhVSebQZU7KUnm5ugRRixkALVkhUwoWfFn1ttWv6Dsc24EiU6XY3Di80D7BsUMZzwZf8GbZd",
	"CcEjFnwo2DcTSDtkJXyUZV2yJmNEgg11EDqKxjMdXlr+oUZ74BnXUBJlATbPBn1C5Flqj1vK/jFLeTRF",
	"4dAzqb0JDcrE34L9RhEWxrIKtlKHyGZANMYegCLy6w1zxvoRkM1hxhmtHLnqzsFcjbZdW5oISjgxPnC+",
	"YKQ+7BqUFEwW7JJ8XjJJ2XeGuQpzWUgUizk+yOYIY3vPr9ZPecbPflo/TdzgaYCtZrCa8uFNrNiIl1KF",
	"ginpfEQdC9TvwDd7GSgVVneW9lIptum3z8XRydWD6H4bupjKaNdIyOPT07+xQ39mfKSGVv+/wTJecq6b",
	"jAcW2ODQHjP+Q2rDE8ivaBw5e8IKkApjc12XJdhDowFtOgR6kCqYqowL0Y/1YjDGZINp7DBHwGhgOxns",
	"Pk5ofzxFHucVyHOsfDzmrfT340vMa5Ks1oKlGSfwNkvTGrUgmqgGoRuU6F+uake1nGRvNZ6k2uQds1bl",
	"TyC/CjflLYSu8quHcDqZgKfMPkrcMG2QbA+OuTpH54pa0cHs7YlZWtemRNaMveBYKZ0j5gpryoa+zkY7",
	"YaUL0xoQOTjf0T7aN8N3j28wYA/opm5/eLXOXHihj5neeimBCYd22Dk0/d7kGvm8QoLd1hRWV1bBS8YE",
	"VrHyjO6fM7I5p3hgt2O1u3M/hB+hrFQzdAWBftct6WekMPW1w16iifomkjnsM+8gnOtBCRNbEgVrKmGu",
	"hsc5qay5lgIF22OvFUFwximZLWYyV2uBVh0ol3Q4qPuKRdx8HgpmwpehXiX6yv41OIHt1tLw0+JnsDF1",
	"J9CjDzVN2cdh+7Mlv27XfO/yvnd537DLa2vzfn3ehX5hPA720Cq6woOsBA8eLdBRp2xFHxnDxXbBXBTT",
	"S6mdB53jj38Uxlw2Xt4ZrQ7voqdu54Xe72S+YyRgEE9Y9HvTzIX+5zah3efX29X0VTdGNrnqNGbaOfav",
	"PtczDgToQV3jAHuqufnan6df9xyEjid8SZm0JtFAr+7H458BAAD//zY+uAXBGAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
