// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: raft.proto

package kioraproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RaftApplierClient is the client API for RaftApplier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftApplierClient interface {
	ApplyLog(ctx context.Context, in *RaftLogMessage, opts ...grpc.CallOption) (*RaftLogReply, error)
}

type raftApplierClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftApplierClient(cc grpc.ClientConnInterface) RaftApplierClient {
	return &raftApplierClient{cc}
}

func (c *raftApplierClient) ApplyLog(ctx context.Context, in *RaftLogMessage, opts ...grpc.CallOption) (*RaftLogReply, error) {
	out := new(RaftLogReply)
	err := c.cc.Invoke(ctx, "/kioraproto.RaftApplier/ApplyLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftApplierServer is the server API for RaftApplier service.
// All implementations must embed UnimplementedRaftApplierServer
// for forward compatibility
type RaftApplierServer interface {
	ApplyLog(context.Context, *RaftLogMessage) (*RaftLogReply, error)
	mustEmbedUnimplementedRaftApplierServer()
}

// UnimplementedRaftApplierServer must be embedded to have forward compatible implementations.
type UnimplementedRaftApplierServer struct {
}

func (UnimplementedRaftApplierServer) ApplyLog(context.Context, *RaftLogMessage) (*RaftLogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyLog not implemented")
}
func (UnimplementedRaftApplierServer) mustEmbedUnimplementedRaftApplierServer() {}

// UnsafeRaftApplierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftApplierServer will
// result in compilation errors.
type UnsafeRaftApplierServer interface {
	mustEmbedUnimplementedRaftApplierServer()
}

func RegisterRaftApplierServer(s grpc.ServiceRegistrar, srv RaftApplierServer) {
	s.RegisterService(&RaftApplier_ServiceDesc, srv)
}

func _RaftApplier_ApplyLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftLogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftApplierServer).ApplyLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kioraproto.RaftApplier/ApplyLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftApplierServer).ApplyLog(ctx, req.(*RaftLogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftApplier_ServiceDesc is the grpc.ServiceDesc for RaftApplier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftApplier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kioraproto.RaftApplier",
	HandlerType: (*RaftApplierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyLog",
			Handler:    _RaftApplier_ApplyLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
