// Code generated by MockGen. DO NOT EDIT.
// Source: ./lib/kiora/kioradb/db.go

// Package mock_kioradb is a generated GoMock package.
package mock_kioradb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	query "github.com/sinkingpoint/kiora/lib/kiora/kioradb/query"
	model "github.com/sinkingpoint/kiora/lib/kiora/model"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// QueryAlerts mocks base method.
func (m *MockDB) QueryAlerts(ctx context.Context, query query.AlertQuery) []model.Alert {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAlerts", ctx, query)
	ret0, _ := ret[0].([]model.Alert)
	return ret0
}

// QueryAlerts indicates an expected call of QueryAlerts.
func (mr *MockDBMockRecorder) QueryAlerts(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAlerts", reflect.TypeOf((*MockDB)(nil).QueryAlerts), ctx, query)
}

// StoreAlertAcknowledgements mocks base method.
func (m *MockDB) StoreAlertAcknowledgements(ctx context.Context, alertID string, ack model.AlertAcknowledgement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAlertAcknowledgements", ctx, alertID, ack)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAlertAcknowledgements indicates an expected call of StoreAlertAcknowledgements.
func (mr *MockDBMockRecorder) StoreAlertAcknowledgements(ctx, alertID, ack interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAlertAcknowledgements", reflect.TypeOf((*MockDB)(nil).StoreAlertAcknowledgements), ctx, alertID, ack)
}

// StoreAlerts mocks base method.
func (m *MockDB) StoreAlerts(ctx context.Context, alerts ...model.Alert) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range alerts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StoreAlerts", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAlerts indicates an expected call of StoreAlerts.
func (mr *MockDBMockRecorder) StoreAlerts(ctx interface{}, alerts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, alerts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAlerts", reflect.TypeOf((*MockDB)(nil).StoreAlerts), varargs...)
}
